name: meditate
description: "Meditate application with countdown timers and customizable durations and a variety of prayer to enhance your practice."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  google_fonts: ^6.2.1
  just_audio: ^0.10.2
  fl_chart: ^1.0.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"